k=189
# starr=["itvayloxrp","wkppqsztdkmvcuwvereiupccauycnjutlv","vweqilsfytihvrzlaodfixoyxvyuyvgpck"]
# starr=['ugcww', 'rrrhsssbbbooyyy', 'rrrlmm', 'ggpprrr', 'nnvvvllmuuu', 'aattthntti', 'lllttxxshnnn', 'hhmzzroorrr', 'ooeeuuffqqh', 'ooodyouyy', 'hhhttfffcdaa', 'oottzzkddd', 'ggajffddgii', 'ueeeuuucccbbueezzz', 'llnookkxxxk', 'tttiiibbid', 'nnnxxxz', 'ghhlljjjyyyfff', 'yyuvvveeer', 'llppiiih', 'sswwwet', 'qneeeyy', 'httnkkkrvvv', 'vvjjvvhhl', 'srrraaqyywwp', 'rpppzzzll', 'rrms', 'lllyyqfff', 'ddjjjaaavvqq', 'ddhhahii', 'ddzzzcoookkv', 'hmoowaax', 'zzzssstttwwfffiiccc', 'ppuuayyyaaa', 'qqdccbbnn', 'cjjjllikkk', 'zztldzzk', 'yyycctvvcccsiiilll', 'vzoow', 'oxxxnnn', 'ddkkkt', 'uuubbfoooen', 'xwwwwiiirrrzzzj', 'opy', 'cyyyqqqppp', 'nnnbbnnyyb', 'rrrffggk', 'pppeuuuxiii', 'wwwvvaaarrr', 'lvvvhddccct', 'ixqqyyyddd', 'mmmwwwuuu', 'dddddbb', 'lnffnn', 'sssvvmvwiiaaaccc', 'hhhpcotoo', 'qkkgmmmww', 'jjjxxaaaa', 'bbuufff', 'fmmffh', 'ffghaaahh', 'gggrrcc', 'ooiuuusssxx', 'rrcccxnn', 'wcpppbbbttxxxnnn', 'wwwqqoodfffvv', 'vvvssuuzccch', 'jpppdyz', 'ihxnni', 'uuttttzmvvdda', 'ccqqqtttiiikkk', 'vvmmmccsscc', 'zzggtttrrrddd', 'gglajeeezzss', 'hssoo', 'xxsssnniwwssqq', 'vvpppgg', 'kkkjjjd', 'beqqqtttjjjddd', 'iiigcczzzxxxvv', 'tnuuukk', 'kkkerrjjjpkk', 'kkrffi', 'rgzzzxxyyy', 'ffwviic', 'ljxxqq', 'rrccxxjjcccrrr', 'hhoooup', 'mmmyyytbbbttcccii', 'fffhjjpppbbxx', 'vvkkkbpppnnmwww', 'jjjsssaaaeettt', 'lljjjrrr', 'sswwaakhhhvvvlllrr', 'uuujjjevvvkkk', 'jjjigwweedkkk', 'ttttyyyffmmcccppf', 'iiiiillldddqrt', 'zzvvvkkuuu', 'ppttqggpppzzz', 'ylllqq', 'yrlj', 'iddzzzmmffzz', 'uucccqqbjjjoojjj', 'eefvvkknnff', 'kkkjjaaccc', 'rrzhhoo', 'yyyxjjj', 'rxxxiddoooeeeq', 'lllffprruzzz', 'pphhhlllxxx', 'aaauuuuuummmay', 'yyyxxxppp', 'daannp', 'jjjxfffuuqq', 'eeqqqnn', 'gggiivv', 'yyrrtttyyyii', 'aaxooyitttth']
# starr=['cavllly', 'ssspppfeaadd', 'nnooossywpvv', 'kkknnccbbb', 'xmmwwmmh', 'uuunnnzzzv', 'dddokkddu', 'bbbbm', 'yyyyynnjjj', 'odddccqqqssvvvzll', 'uuvpoo', 'rccmmmxxtt', 'opppceee', 'ppwwwkkhhw', 'xmmqqqjj', 'hhhssnnnuwwwtt', 'llteeeccfff', 'nnnnttrllq', 'jjrrbg', 'vvvtttjjaaww', 'oooqqqjpdm', 'fffzriinnn', 'nppyjhhh', 'ddkkkxxxnnccagg', 'dgggbbbww', 'zbbbffjble', 'ttuuqqjjjz', 'xxxtyyyettt', 'ammq', 'ccccchjjeee', 'eeemmk', 'tttzzzyccaabb', 'dddxxsssii', 'zzssaaa', 'mgggfffhhhp', 'fffcddd', 'hhmeooonfff', 'mmpjjaa', 'ffmmmbbbqqqhhddiii', 'assybbxxxrrr', 'dddmmmzjjj', 'uurrwww', 'djjmeeddf', 'ziattnn', 'diibehjjjb', 'bbbeeshh', 'uuuzsccnjjjeee', 'rrqqwoo', 'cccrrooeeiiig', 'ngggssb', 'nnwoowwwhyyj', 'ppppwwwyffee', 'eeesssaah', 'oozmmmy', 'ddmmmrrrug', 'xkkknnnlkkkd', 'fffqeeggg', 'iiyygeer', 'kyjttt', 'zeelllrr', 'jjjeeelccqq', 'mmmeeeeeuqww', 'puuukyyy', 'mlleesssdddyyyuurrr', 'hnng', 'qqmmwggnnnddzzz', 'jjddqqq', 'fkuuuflsspp', 'dddpppmmmvv', 'kkpyyyff', 'nayyylll', 'yyyeeemvvvmm', 'uucccjjjjjrrr', 'qzzrrreeqqm', 'uummbbbr', 'vmdddthhx', 'jqqqe', 'gzztttwww', 'llnnnxhhaaahhhxxww', 'tttyyyy', 'yhhhvvollli', 'gggccccqqfgggaaq', 'zzsnnn', 'dddr', 'bzzzcgmyyy', 'vrrrcyyynnn', 'ooqqqmmwww', 'jjffziijzz', 'jemmmv', 'czzzpppyvvvddd', 'ooorqvvvrjjj', 'tffaaaaatt', 'maaaxlllooo', 'mmmhhhbbblll', 'xxuggbbs', 'llluuulllh', 'bbbrrrhhkk', 'vvvvvssrrccc', 'kkepppphhnuuu', 'xxsssdddyyeee', 'uddssqqqoo', 'vvvyoo', 'plllymmmvvdd', 'xxbbbqqabbqqfffnnn', 'iiiyyooogttbbb', 'zzoaajbbbeed', 'pppvvb', 'cccuuxxxiiariii', 'llddnnnzjjvvvwccc', 'yyfffddvcc', 'llrryysssqqwwwnnq', 'alllhhhhbbbjjjhhh', 'uuaggyyycccqqeaa', 'jjjxxooomsssddd', 'ttvvvppuuaa', 'bhhhhc', 'sssmmwwwz', 'bbttb', 'iiilllawwhhh', 'dddursssnnhhll', 'pxxxc', 'oodppp', 'irrwweefcccyyvvv', 'pccrrr', 'aaacccllltt', 'mmmti', 'iiizzzfeeffyppp', 'zzzhzzzpjjjddlll', 'gggvvhaa', 'mgghhhno', 'dddzzzjjjqyyffsss', 'bwbbaayyylleee', 'ccmmmnnn', 'qssvuuwwd', 'mmodd', 'apzbzzzq', 'qqvdddpvvvhh', 'eessspppjeey', 'zzzdslllz', 'aafwwlllvvv', 'oooyxxx', 'uuuuubb', 'kkkzkkv', 'cccbbbuuggg', 'hhhniiild', 'kccjju', 'qqqwwlllwddmmbbbddd', 'nsssuuuuu', 'xmmojnn', 'rrrppobbbjjjf', 'nnfffllfff', 'tttjyyyuuugyq', 'rrjlllkkk', 'jjjcccsskkddq', 'rrrrrlkfffnnnxwxaaa', 'zzzszzzonnddc', 'lpppppwccc', 'rrnnmxx', 'iiivvii', 'asxxxuuuk', 'xowwlll', 'zgbbtvvzzzrgg', 'sssaaaeempppuuukkk', 'dkkrrqqqcvv', 'gggjjjyyyjjj', 'uufftttqqqxxrr', 'mmmyggg', 'wozlllxe', 'qqaaswwwk', 'kkpppwwwbbb', 'rrqqqyynnneii', 'auuusjsaa', 'cciicjjj', 'aaajccjjjevvda', 'zzzmlccqqqmm', 'eaappxxxll', 'ooottdd', 'pppnnnullvvvkkk', 'oodffoonnnmmw', 'gcxxxmmmsxxx', 'xxxmkdddzrrr', 'qcjjjooxsssq', 'rcccnnrrffgyyjj', 'ccciiijjvfff', 'yyyooobh', 'wwddffgggyyygfff', 'ggjxxxqqqvnnzzz', 'smwvezz', 'dfffpkpimm', 'zxxppppkkk', 'pppllppxxaa']
starr=['gggllln', 'vvnnntrrwwggg', 'cfccyjjj', 'qqqoofiiu', 'lllgggrrrjjjwx', 'qwwwhhhjj', 'qpppiiifffatt', 'fffffiwwaiihhhnnn', 'mmhrwwwyymmmlllll', 'ttjjqeei', 'xxxmzzzttt', 'nnntttwwvvvafe', 'fffuuuvvveeewwwycck', 'eoooxxxubbb', 'wllmmmmmmxxo', 'xdbupppaahhhll', 'lqgggww', 'ehhmmmcffwww', 'xqwwwjjiiqqbb', 'zwwwrrhwwqqqkkk', 'vviooo', 'ynnnvviivo', 'vlyy', 'qvvjgggaeejjj', 'mmeyuub', 'xxiiirvvv', 'kkkrcc', 'fftvv', 'xxxczzzkkffbyyye', 'ccddoogmm', 'mmssskkyyyffffxxx', 'qqqtttgggguukk', 'vtooqq', 'ppttxxcccqqq', 'xhvvuuua', 'ikkhhhvvvxxooo', 'guxkk', 'xxhhhlll', 'mmnnntttxxx', 'oooyyff', 'zpppmmm', 'yyymmmmnnnbblll', 'zzzjusssiiimmm', 'wwuugmmm', 'pggggkk', 'eeexi', 'uueeuuyyo', 'eeeggzzzeeeggged', 'oouuuuuqqiii', 'mmmaaajjjnnkkk', 'zzrcfttcyyyrjj', 'eujll', 'offfeeeooyydddinn', 'eejjjvvuij', 'pppnvvv', 'rrrkkuucnng', 'rrrdddpppqctt', 'vvxxxcggmm', 'ntttcccx', 'oocvvvrr', 'rggfffeeppprrr', 'qqfffk', 'hdddg', 'fffbbjvvkoo', 'wwxxxrraaazzbbb', 'zznnbbpp', 'iiirrrtttaa', 'vvwwaffkkcccyyy', 'hbbqqqvvqq', 'ddweeemmmmmmjjj', 'niiippcchhhxxwww', 'eeebbnnnuuupp', 'wwwhhhqeey', 'ulldddbbbqgss', 'juuuneeeeo', 'jbbbpppz', 'hhbbpppkkuuuyttt', 'ffuunn', 'tttpppggrrsbggg', 'rrrnnwwwwwufffoo', 'qqqqbppp', 'xxxzjjjdnn', 'eeerrwppp', 'gggeiiifho', 'zzezzzl', 'mmhytttqq', 'fnnnh', 'iiiddgggxxx', 'ijjjeeeqnnff', 'pccsss', 'seayyygzzz', 'ccrrtttxxx', 'iiiqqsyttnn', 'nnnccciiifvvv', 'ssddr', 'ephh', 'uossmm', 'uqqwwws', 'zzaaxxxal', 'pppceevnaaat', 'ppyyykkkccckhhh', 'yrrjju', 'hbzzbbbrrmjjv', 'kkkivvvdpp', 'rrryyyjttt', 'kkkybbwwwjpppn', 'qfffuussswws', 'vveejjjgggf', 'jjuuuddzzrwwqqjj', 'liiiiiijjjfnnn', 'ddvt', 'wwddttnssszzzuuu', 'bbbvbbbcc', 'xxhmvvrrrhhh', 'qaatttffflgg', 'qqffzkkk', 'uuuhnnuhhhr', 'bbbhhheehhqqqeee', 'aalllmmooooo', 'nuuucccpzzz', 'cssskkkukk', 'bbbrfff', 'cccllbaannnaaccco', 'uxzzttvv', 'vfffss', 'yoov', 'ndkkkkkkd', 'feeyydakkk', 'aannoaaaa', 'zzzppoorreee', 'rrlllmgguutt', 'oooopppddhhi', 'ddchhhnn', 'gccjjjzzzlzz', 'gggvvcckqttrrr', 'ytttoxxxhh', 'yyggennnvvv', 'yyoybh', 'buuutttlwwg', 'yyygggrrrrrraaarrr', 'rrdddqqcc', 'eerdddhhhkk', 'kkkmmmlm', 'tytttruuyyt', 'qqkkkbaqq', 'tfccwwwfddd', 'nnnaammmgg', 'ttvvvuu', 'mmmbbbuaaa', 'xxnnnuupf', 'ubbwoowwweee', 'qqqbuuoo', 'vaffttt', 'iiieecjjj', 'neorrjjhhh', 'dwwqqkkssxx', 'ccoooddden', 'ookbr', 'vvvkkkkpppttoohhh', 'lvvbzzfffrrrd', 'bwwh', 'gkprrm', 'ipdddffrhhhxx', 'tttppgggtttpppqqkkk', 'eeiiiskkkjjjeee', 'kkkeeebbaaaxx', 'pcccgggpppzzur', 'xxxjcc', 'bbzzzoo', 'mmmggxxxqqqcctttaaa', 'sssqqaagrrr', 'ccttmmmmfpp', 'nnnkuthhhxaaas', 'eenooomhhyyyzzzmmm', 'xcccpnnffwwwzz', 'jjjyw', 'llhtoodpp', 'yynnccgggpppiiig', 'kkkoooyyym', 'niiiq', 'qqyyyhhaaaaa', 'hyyyyyyrsssm', 'aaalsskk', 'ssffwww', 'yyynnvff', 'wwwzttnnncc', 'jsszltttxxdduuu', 'udcccqqa', 'bbbmmjiiidubbf', 'kkvxxjjjzzz', 'muuzff', 'bvvdddwwwsss', 'xxxjxxccj', 'rffirrrnx', 'ppjjjppplaaal']
def longest_consec(strarr, k):
  if k<=0 or k>len(strarr):
      return ''
  prev_longest=""
  for x in strarr:
    current_longest=x
    i=1
    current_longest=x
    while(i<k and strarr.index(x)+i<len(strarr)):
      current_longest+=strarr[strarr.index(x)+i]
      i+=1
    if len(current_longest) > len(prev_longest):
      prev_longest=current_longest

  print(prev_longest)

longest_consec(starr,k)
